name: Run Tests
on:
  push:
    branches-ignore:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install dependencies - node_modules cache
        id: node_modules_cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies - npm install-clean
        if: steps.node_modules_cache.outputs.cache-hit == false
        run: npm install-clean

      - name: Run tests
        run: npm run test-ci
